### ISSUE TITLE
준비중이라고뜨고 다운로드가 진행되지않음

### ISSUE THREAD

**Issue by sangeunbozi** [lsh4711/rabbit-downloader#10]
다운로드진행이 안됩니다

**Comment by lsh4711** [comment]
안녕하세요.
메일로도 문의주셔서 답변드렸습니다.

**Comment by lsh4711** [comment]
안녕하세요.
이용 중이신 환경이 모바일과 PC 중 어느 것인지와 운영체제(windows, linux, ios... 등등)에 대해 알려주실 수 있을까요.

**Comment by lsh4711** [comment]
문의주신 다운로드 중단 문제는 현재 1.5 버전에서는 해결된 것으로 판단되어 이슈를 종료하겠습니다.
