### ISSUE TITLE
폴더 지정화면으로 넘어갈때 오류가 납니다

### ISSUE THREAD

**Issue by kanazawdh** [lsh4711/rabbit-downloader#13]
ohldgfmhhadhcemnbepnciaoanbbaeba이(가) 차단됨
Chrome에서 차단한 페이지입니다.
ERR_BLOCKED_BY_CLIENT

별개의 창이 열리면서 이런 메세지가 출력되고 다운로드가 진행되지 않습니다

**Comment by lsh4711** [comment]
*내용 추가해서 메일드립니다.*
사이트가 허용되지 않은 경우 
https://blog.naver.com/nitrogehne/220883311611
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-05-20 (월) 23:47:18 (GMT+09:00)
Subject: [lsh4711/rabbit-downloader] 폴더 지정화면으로 넘어갈때 오류가 납니다 (Issue #13)

ohldgfmhhadhcemnbepnciaoanbbaeba이(가) 차단됨
Chrome에서 차단한 페이지입니다.
ERR_BLOCKED_BY_CLIENT
별개의 창이 열리면서 이런 메세지가 출력되고 다운로드가 진행되지 않습니다

**Comment by lsh4711** [comment]
1.4 버전에서 추가 설정 페이지가 차단되는 문제가 해결되었으므로 이슈를 종료하겠습니다.
