### ISSUE TITLE
차단 당했습니다ㅠㅠ

### ISSUE THREAD

**Issue by geniussjt** [lsh4711/rabbit-downloader#14]
ohldgfmhhadhcemnbepnciaoanbbaeba이(가) 차단됨Chrome에서 차단한 페이지입니다.
ERR_BLOCKED_BY_CLIENT 차단 되다고 나옵니다
![24-02-13  1757223063811232226_p0](https://github.com/lsh4711/rabbit-downloader/assets/47520785/f44723ae-a09d-4ee7-a703-fd253b34bdcd)
차단 당했습니다ㅠㅠ하하
어찌하면 좋을까요...

**Comment by lsh4711** [comment]
안녕하세요 
얼마전에도 비슷한 문의가 있었는데

아마 토끼 사이트나 토끼 다운로더에서 차단되신 것은 아니고
크롬이나 애드블락에서 확장프로그램 주소를 차단해서 그런거같아요
최근 토끼 다운로더 다운로드 방식의 변경으로 인해 새 페이지가 열려야하는데 막히시는거 같습니다.
아마 사용자가 허용 설정해줘야할거같아요.

예상 주소1: chrome-extension://ohldgfmhhadhcemnbepnciaoanbbaeba/options.html

예상 주소2: chrome-extension://ohldgfmhhadhcemnbepnciaoanbbaeba/index.html

그 분이 해결 되셨는지 소식이 없으셔서
링크는 달아드리는데 도움이 되실지 모르겠습니다.
https://github.com/lsh4711/rabbit-downloader/issues/13

해결이 바로 안되셔도 메일 통해서 추가 문의 주시면 최대한 도와드리겠습니다.

그리고 다음 1.4버전에선 1대1 문의 기능이 완성되어 편하게 문의하실수 있습니다.
이번주 안으로 업데이트 될 것으로 예상됩니다.

***
토끼 다운로더를 이용해주셔서 감사합니다.
깃허브 별모양과 확장스토어 리뷰 한번씩 남겨주시면 개발하는데 큰 힘이 됩니다.
***

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-05-29 (수) 03:21:42 (GMT+09:00)
Subject: [lsh4711/rabbit-downloader] 차단 당했습니다ㅠㅠ (Issue #14)

ohldgfmhhadhcemnbepnciaoanbbaeba이(가) 차단됨Chrome에서 차단한 페이지입니다.
ERR_BLOCKED_BY_CLIENT 차단 되다고 나옵니다
24-02-13.1757223063811232226_p0.jpg (view on web)
차단 당했습니다ㅠㅠ하하
어찌하면 좋을까요...

**Comment by geniussjt** [comment]
![24-02-13  1757223063811232226_p0](https://github.com/lsh4711/rabbit-downloader/assets/47520785/6770389f-dea3-4538-ad8d-128b2d65d7f0) 폴더 설정하면 알집으로 다운이 안되고 폴더로 다운이 되는데...중간에 중지됩니다  
1.4버전 기다릴 수 밖에 없네요^^

**Comment by lsh4711** [comment]
1.3버전 이후로는 압축없이 즉시 폴더로 다운로드되는 것이 정상적인 동작이긴합니다만
중간에 멈춘다는 말씀은 일부는 다운로드 되긴 하는 것가요?
아니면 아예 다운로드가 되지않으시나요?
올려주신 사진으로 봤을때는 다운로드 폴더 지정 및 권한부여가 아직 안된것으로 보여서요.

자세한 문제상황 공유해주시면 바로 도움드리겠습니다.


-----Original Message-----

**Comment by lsh4711** [comment]
우선 추가 설정페이지가 열리는것으로 보먄
다운로드 폴더 지정 및 권한 부여만 하면 되실 것 같아서 방법부터 미리 보내드립니다.

폴더 선택 -> 다운로드 하실 폴더 선택하시고나서

두가지 방법으로 진행 가능하십니다.
1. 곧바로 표시되는 폴더 재선택 메시지를 따라 같은 폴더를 다시 선택 후 ‘방문할 때 마다 (권한)허용’ 누르시면 앞으로는 별다른 설정없이 다운로드 가능하세요.
2. 혹여나 폴더 재선택 메시지가 안보이거나 창을 닫아 버린경우에는
추가설정창을 닫은 다음 새로 열어서 같은 폴더를 다시 선택하시면됩니다.

그 후 해결 되셨는지 말씀 한번만 부탁드릴게요.
감사합니다.

-----Original Message-----

**Comment by geniussjt** [comment]
친절한 설명 정말 감사합니다 다운이 잘되는데..요 근데..요 다운 속도가 조금 늦을 것 같습니다ㅠ_ㅠ
![24-02-13  1757223063811232226_p0](https://github.com/lsh4711/rabbit-downloader/assets/47520785/ea74f079-47fc-492f-bece-0e4cc459a2b0)암튼 새벽이었는데 새벽까지 정밀 대단히 수고많으셨습니다 그리고 정말로 감사합니다ㅠㅠb척

**Comment by lsh4711** [comment]
도움이 되어 다행입니다.
다운로드 속도가 초기 버전보다 느려진 이유는 1.2 버전 업데이트 당시에 토끼 사이트의 차단 정책이 강화되어 
시간 당 보내는 요청이 많을 때 사이트에서 차단당하는 문제가 있었기때문에 시간 당 요청 횟수를 의도적으로 안전하게 늦춰놓았습니다.
그래서 인터넷 속도와 관계없이 다운로드 속도가 고정적으로 느리게 보일 수 있습니다만
나중에 여러번 테스트하며 좀 더 적절한 시간을 찾아서 단축시켜보겠습니다.

필요하신 기능이 있거나 추가 문의 사항 있으시면 언제든지 메일 주세요.
좀 더 사용해보시고 토끼 다운로더가 만족스러우시다면 깃허브 별 모양 클릭과 스토어 리뷰 한번씩 부탁드리겠습니다.

-----Original Message-----

**Comment by geniussjt** [comment]
주인장님 죄송하지만 다시 다운이 중단에 멈춰요ㅠ_ㅠ다운은 되지만 다운 10분 후에 먹통입니다
아침에 잘됩니다...새벽에 인터넷 초기화도 했고...이제 뭐가뭔지 모르겠고 지칩니다..ㅠ_ㅠ업데이트 기다리겠습니다 
화이팅!!

**Comment by lsh4711** [comment]
다운로드가 작동은하는데 중간에 종료되는 것은 사용자나 토끼 다운로더의 문제가 아니고
토끼 사이트에서 크롤링 봇을 막기위한 조치 때문일거에요.
그래서 페이지 이동없이 너무 오래 방치하면 다운로드가 중단되기도 해서 
이럴땐 페이지를 새로고침하거나 다른 페이지로 이동 후에 다운로드 재개 버튼을 누르셔야 할 것 같습니다.
그리고 잘아시겠지만 만화, 웹툰, 소설 별로 사이트가 다른데
다운로드가 종료되는 콘텐츠 타입에 맞춰서 각 타입별로 맞는 사이트를 접속을 해야합니다.

혹여나 해결이 안되더라도 지속적으로 추가 정보를 제공해주시면 최대한 도움 드릴 수 있도록 하겠습니다.
불편하시거나 문제가 생길때마다 번거로우시더라도 문의 부탁드릴게요.
개발하면서 테스트를 꼼꼼히 할 여유가 없이 업데이트를 하고 있기 때문에
사용자의 적극적인 협조가 개선하는데 큰 도움이 됩니다.

-----Original Message-----

**Comment by lsh4711** [comment]
지금 사용이 너무 불편하시면 화면공유가 가능한 디스코드 등을 통해 1대1로 봐드리겠습니다.
-----Original Message-----

**Comment by geniussjt** [comment]
지금 F5 페이지를 새로고침하거나 다른 페이지로 이동 후에 다운로드 재개 해봤는데...계속 중간에서 먹통됩니다
현재 크롬이나 애드블락에서 한번 차단 당하면...정말..끝이네요...방법이 없는 것 같습니다...ㅠ_ㅠ반포기...그냥 기다리겠습니다...

**Comment by lsh4711** [comment]
그러면 조금만 기다려주시면 1.4버전에서 문의 기능이 추가되니 기존보다는 문의나 소통하기 편하실거에요.
문제를 해결하실 수 있도록 지속적인 도움을 드리겠습니다.
-----Original Message-----

**Comment by lsh4711** [comment]
1.4 버전에서 추가 설정 페이지가 차단되는 문제가 해결되었으므로 이슈를 종료하겠습니다.
