### ISSUE TITLE
다운로드 할려고 하니 로그인이 실패했다고 하는데요

### ISSUE THREAD

**Issue by jangjunc** [lsh4711/rabbit-downloader#20]
다운로드 할려고 하니 로그인이 필요합니다 후에 로그인이 실패했다고 하는데요
어떻게 해야 하나요?
토끼든 구글 사이트든 다 로그인이 되어있는 상태에요

**Comment by lsh4711** [comment]
번거로우시더라도 로그아웃을 1회 진행하고 재 로그인하시면 해결될 것 같습니다.
위 방법으로 해결되셨더라도 원인을 파악하고 문제를 해결할 수 있도록 마지막으로 로그인한 날짜를 대략적으로라도 회신해주실 수 있을까요?
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-06-19 (수) 00:22:34 (GMT+09:00)
Subject: [lsh4711/rabbit-downloader] 다운로드 할려고 하니 로그인이 실패했다고 하는데요 (Issue #20)

다운로드 할려고 하니 로그인이 필요합니다 후에 로그인이 실패했다고 하는데요
어떻게 해야 하나요?
토끼든 구글 사이트든 다 로그인이 되어있는 상태에요

**Comment by jangjunc** [comment]
처음에 그냥 구글과 토끼 모두 로그아웃하고 재로그인후 시도해도 안되서 아예 모두 로그아웃하고 브라우저를 껐다 켜서 다시 로그인 후 시도해도 로그인이 실패했다고하네요............

**Comment by lsh4711** [comment]
개발 환경 및 테스트 환경에서는 모두 로그인 및 로그아웃이 잘 되는 것 같아서
서버 로그도 확인해보았지만 특이사항은 없었으며 다른 사용자들은 로그인이 되는 것으로 확인되었습니다.
문제를 해결하실 수 있도록 도움을 드리고 싶은데 괜찮으시다면 디스코드로 화면 공유해 주실 수 있으실까요?

**Comment by jangjunc** [comment]
제가 디스코드 화면공유는 해본적이 없어서...... 어떻게 해야 하나요?

**Comment by lsh4711** [comment]
지금 채널 생성하고 주소 남겨드릴테니 들어와보시겠어요?

**Comment by jangjunc** [comment]
네 주소알려주세요

**Comment by lsh4711** [comment]
https://discord.gg/23YaprQx
입니다.

**Comment by lsh4711** [comment]
#21

**Comment by jangjunc** [comment]
jangjun@gmail.com
입니다

**Comment by lsh4711** [comment]
@jangjunc
현재 스토어 검수 중인 1.9 버전에서 타 브라우저도 호환되도록 개선되어 안내드립니다.
