### ISSUE TITLE
다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [lsh4711/rabbit-downloader#25]
어제는 잘 되는데 오늘 다운이 자꾸 중단 됩니다...

**Comment by lsh4711** [comment]
#26

**Comment by geniussjt** [comment]
지금 모든 만X X툰이  다운이 안됩니다

**Comment by lsh4711** [comment]
테스트 해보니 문제는 없습니다만 원인은 계속 찾아보겠습니다.
죄송하지만 원인을 발견하고 해결할 때 까진 타 다운로더 이용하셔야할 것 같습니다.
