### ISSUE TITLE
엣지에서는 로그인이 불가능한건가요?

### ISSUE THREAD

**Issue by voskj** [lsh4711/rabbit-downloader#27]
개발자님의 노고에 감사드립니다
크롬에서는 문제없이 잘 사용중이고 
엣지에서는 로그인이 되지 않는데 어떤 해결방안이 있는지 궁금합니다 

OS 는 윈도우 10 홈 이고
사용중인 브라우저는 엣지 와 크롬입니다

**Comment by lsh4711** [comment]
안녕하세요.
이용해주셔서 감사드립니다.

우선 이 이슈(#21)를 한번 참고 부탁드리옵고
보시면 웨일 브라우저에서도 크롬 인증을 지원하지 않고 있는데
제가 찾아보니 엣지에서도 마찬가지로 제대로 지원되지 않고있네요..
![image](https://github.com/lsh4711/rabbit-downloader/assets/120231876/e41a89aa-8ff7-4a2e-a408-179a24feb36d)

해당 이슈의 내용대로 타 브라우저 호환을 위해 독립적인 url방식의 Oauth 로그인을 추가하려고 준비중이니 조금 기다려주시면 감사하겠습니다.

**Comment by lsh4711** [comment]
@voskj
현재 스토어 검수 중인 1.9 버전에서 타 브라우저도 호환되도록 개선되어 안내드립니다.
