### ISSUE TITLE
다운로드와 로그인 불가 현상

### ISSUE THREAD

**Issue by Luciferia0626** [lsh4711/rabbit-downloader#32]
윈도우, 크롬 사용중입니다
다운로드 클릭시 로그인이 필요합니다/로그인에 실패했습니다만 나타나고 종료됩니다
앱 옵션을 통해 Continue with Google 클릭시에도 로그인이 실패했습니다가 나타난 후 종료됩니다
옵션은 모두 On,Off가 가능하나 최상단의 켜짐 버튼은 조작이 불가능합니다
우하단에는 알림버튼과 +버튼 두가지만 존재하고 +화면 클릭시 크롬 페이지가 뿌연 흰색으로 변하지만 아무 창도 나타나지 않습니다
확장프로그램을 한번 삭제한 후 재다운로드, 컴퓨터의 재부팅까지는 실행했으나 효과가 없었고 컴퓨터 지식 부족으로 이 이상 뭘 해야할지 몰라 도움을 요청합니다

**Comment by lsh4711** [comment]
@Luciferia0626
당시에 크롬 구버전만 사용 가능하셨던 상황으로 기억하는데
현재 스토어 검수 중인 1.9 버전에서 타 브라우저도 호환되도록 개선되어 안내드립니다.

**Comment by Luciferia0626** [comment]
아쉽지만 여전히 로그인 불가한 것 같네요 ㅎㅎ;;
그래도 메시지에는 감사드립니다

2024년 9월 7일 (토) 오전 12:59, lsh4711 ***@***.***>님이 작성:
