### ISSUE TITLE
크롬에서 로그인 안되는 증상

### ISSUE THREAD

**Issue by jlee7385** [lsh4711/rabbit-downloader#34]
Continue with google 눌러도 로그인이 안되는 증상이 생깁니다.
크롬에서 아이디 바꿔서 로그인도 해보고 아예 크롬을 삭제 후 재설치를 해봐도 안되네요.
OS는 Windows11 x64 이고 기존에 잘 사용하다가 오늘 아침부터 문제가 생겼습니다.
![image](https://github.com/user-attachments/assets/64bb86b2-7c6b-4775-b0f3-3c6b040d8270)

**Comment by lsh4711** [comment]
이메일 주소를 남겨주시겠어요?

**Comment by lsh4711** [comment]
토끼 다운로드에 연동된 계정 이메일을 남겨주세요.

**Comment by jlee7385** [comment]
ns327ns@gmail.com 계정으로 사용하고 있었고 dsx100v 계정으로도 테스트 해 봤습니다만 모두 로그인에 실패했습니다. 로그인 된 상태로 남아 있는 다른 PC가 있어서 거기서 몇 번 다운로드 시도해 봤는데 1~2초 후에 다운로드를 중단합니다 라는 메시지만 나옵니다

**Comment by lsh4711** [comment]
현재 스토어 검수 중인 1.9 버전에서 로그인 기능을 개선했는데 업데이트 이후로도 문제가 발생하는지 확인 부탁드리겠습니다.

**Comment by pickyni** [comment]
> 현재 스토어 검수 중인 1.9 버전에서 로그인 기능을 개선했는데 업데이트 이후로도 문제가 발생하는지 확인 부탁드리겠습니다.

 검수 끝나야 업데이트 가능한가요? 다운로드 하려고 하면 로그인하라고 떠서 진행이 안되는데 1.9 업데이트 수동으로 하는 방법이 있는지요

**Comment by lsh4711** [comment]
네 검수가 끝나면 자동으로 업데이트되는 것으로 알고 있습니다.
아직 검수중이고 보통 2~3일 정도 소요되는 것 같습니다.
자동 업데이트가 되지 않으신다면 재설치하는 방법도 있습니다.

**Comment by jlee7385** [comment]
1.9 버전으로 삭제 후 재설치 했고 설치 후 처음엔 잘못된 사이트 주소로 들어가는 문제가 있었는데 1~2분 지나고 접속 잘 됩니다.
로그인 / 다운로드 모두 잘 되고 체감 상 다운 속도가 빨라진 것 같습니다.
정말 감사합니다.

**Comment by Kasmys** [comment]
> 현재 스토어 검수 중인 1.9 버전에서 로그인 기능을 개선했는데 업데이트 이후로도 문제가 발생하는지 확인 부탁드리겠습니다.

1.9버전 로그인 안됩니다. 토끼 다운로드 설정 창에서는 로그인 시도해도 별 반응이 없고 마나토끼 사이트에서 다운로드 누를 시엔 로그인 실패가 뜹니다.

**Comment by rudy7788** [comment]
동일증상입니다. 다운로더는 1.10버전이며
윈도우10, 크롬129.0.6668.101, 구글계정 ysw7788@gmail.com 입니다.
