### ISSUE TITLE
구글 로그인에 실패했습니다.

### ISSUE THREAD

**Issue by teampch** [lsh4711/rabbit-downloader#40]
안녕하세요. 토끼 다운로더를 감사히 사용 중입니다.
구글 로그인을 시도하다가 실패하는 현상이 발견되어 확인 요청 드립니다.

- 사용중인 운영체제 = 윈도우11
- 사용중인 브라우저  = 크롬
- 문제 상황 = 구글 로그인 버튼을 터치하면 로그인 중이라고 나온 후 다른 경고 메시지 등이 없이 로그인에 실패합니다.(실패했다는 메시지도 없었습니다.)
- 문제 계정 = teampch@gmail.com

**Comment by lsh4711** [comment]
안녕하세요.
요새 서버 상태를 잘 확인하지 못해서 방금 확인해보니 엊그제쯤부터 서버에 문제가 생겼던 것 같습니다.
이제 잘 되실거에요.
