### ISSUE TITLE
로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by syntaxjae** [lsh4711/rabbit-downloader#42]
운영체제: 윈도우 10

사용중인 브라우저: 크롬 ( 마이크로 엣지도 해봄)

문제 상황: continue with goolge를 눌러도 반응이 없음

jae9969@gmail.com

![스크린샷(478)](https://github.com/user-attachments/assets/589f12c6-18c0-4f48-bbd6-8b5e3bfeb820)

**Comment by lsh4711** [comment]
확인해보았는데 지금은 서버에 이상이 없고 저도 다시 로그인 해보았는데 잘 되고 있네요.
기존에는 잘 되셨던건지 신규 사용자이신지도 설명 부탁드리겠습니다.
