### ISSUE TITLE
다운로드가 중지됩니다

### ISSUE THREAD

**Issue by jangshik** [lsh4711/rabbit-downloader#46]
공통사용중인 운영체제
윈도우10, 크롬 127
예시) 크롬문제 상황
화면에 표시되는 정보 등 최대한 자세하게 설명부탁드립니다.

북토끼 
https://booktoki348.com/novel/9414351?stx=%EC%9D%B4+%EB%8F%85%EC%9D%BC%EC%9D%80+%EC%B4%9D%ED%86%B5
다운로드 시도를 하면 별다른 알림 없이 중지상태로 들어갑니다. 저장공간 허용은 수행하였습니다

좋은 프로그램 공유 감사드립니다.

**Comment by lsh4711** [comment]
안녕하세요.
확인해보겠습니다.

**Comment by lsh4711** [comment]
이제 다운로드되실거에요.
기다려주셔서 감사합니다.

**Comment by hijinious** [comment]
안녕하세요
어제는 북토끼 잘 다운되었는데 오늘 써보니까 또 중단이 됩니다
