### ISSUE TITLE
북토끼 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by assstone** [lsh4711/rabbit-downloader#47]
ㅇ윈도우11 / 크롬

ㅇ재시작을 눌러도 다운로드가 되지 않고 멈춥니다.

ㅇ웹툰은 다운로드 되는데, 
북토끼는 다운로드가 안됩니다.

ㅇ다운로드 안되는 북토끼 주소 : 
https://booktoki349.com/novel/6216?stx=%EC%B2%9C%EC%9E%AC+%EB%AC%B4%EB%A6%BC

감사합니다. 좋은 하루 되세요...

**Comment by lsh4711** [comment]
이슈 제보 감사합니다.

무료로 운영하려다 보니 비용적인 부분 때문에 서버를 저사양으로 운영하고 있습니다만
근래 이용하는 분들이 굉장히 많아져서 이용자가 몰리는 시점 이후로 로그인이나 기타 기능에 문제가 생기네요.
서버를 재부팅했으니 당분간은 문제가 없으실거에요.
제가 일정 떄문에 당장 손을 대기는 어려워 다음 패치 전으로 시간을 내서 개선하겠습니다.

혹시나 다시 안되는 경우 제보해주시면 감사하겠습니다.

**Comment by lsh4711** [comment]
이슈 제보 감사합니다.

무료로 운영하려다 보니 비용적인 부분 때문에 서버를 저사양으로 운영하고 있습니다만
근래 이용하는 분들이 굉장히 많아져서 이용자가 몰리는 시점 이후로 로그인이나 기타 기능에 문제가 생기네요.
서버를 재시작했으니 당분간은 문제가 없으실거에요.
제가 일정 떄문에 당장 손을 대기는 어려워 다음 패치 전으로 시간을 내서 개선하겠습니다.

혹시나 다시 안되는 경우 제보해주시면 감사하겠습니다.

**Comment by lsh4711** [comment]
이슈 제보 감사합니다.

무료로 운영하려다 보니 비용적인 부분 때문에 서버를 저사양으로 운영하고 있습니다만
근래 이용하는 분들이 많아져서 이용자가 몰리는 시점 이후로 로그인이나 기타 기능에 문제가 생기네요.
서버를 재시작했으니 당분간은 문제가 없으실거에요.
제가 일정 떄문에 당장 손을 대기는 어려워 다음 패치 전으로 시간을 내서 개선하겠습니다.

혹시나 다시 안되는 경우 제보해주시면 감사하겠습니다.

**Comment by lsh4711** [comment]
이슈 제보 감사합니다.

무료로 운영하려다 보니 비용적인 부분 때문에 서버를 저사양으로 운영하고 있습니다만
근래 이용하는 분들이 많아져서 이용자가 몰리는 시점 이후로 로그인이나 기타 기능에 문제가 생기네요.
서버를 재시작했으니 당분간은 잘 되실거에요.
제가 일정 떄문에 당장 손을 대기는 어려워 다음 패치 전으로 시간을 내서 개선하겠습니다.

혹시나 다시 안되는 경우 제보해주시면 감사하겠습니다.
