### ISSUE TITLE
다운로드 자동중단 현상입니다

### ISSUE THREAD

**Issue by voskj** [lsh4711/rabbit-downloader#48]
사용중인 운영체제
윈도우10 home 버전

사용중인 브라우저
Chrome
버전 128.0.6613.85(공식 빌드) (64비트)

문제 상황
항상 수고가 많으십니다
다름이 아니라 북토끼에서 다운로드를 누르면 목록에 추가는 되지만 
자동 중단이 되어버리는 현상이 나타납니다
몇일전 같은 증상으로 해결 하셨다는 글을 보았는데 2~3일후 부터 다시 발생하네요
작품이나 회차에 상관없이 자동 중단이 되어버립니다
바쁘시겠지만 확인 부탁드립니다

**Comment by lsh4711** [comment]
금일 새벽부터 또 문제가 생긴 것 같아 조치를 했습니다.
이제 되실거에요.
아직 해결된 것은 아니고  현재 개선 중입니다.
