### ISSUE TITLE
다운로드 표시가 없습니다

### ISSUE THREAD

**Issue by GregHKim** [lsh4711/rabbit-downloader#51]
![스크린샷 2024-09-05 144825](https://github.com/user-attachments/assets/d91d28a5-9a50-4211-8335-7b7d58b1ab8c)

기타 옵션들은 뜨는데 사용설명서에 있는것 처럼 다운로드 버튼은 안보이네요.. 크롬 스토어에서 받았고 크롬은 최신버전입니다

**Comment by GregHKim** [comment]
추가설정을 눌러도 나오는것이 없구요... 저만 그런가요?

**Comment by lsh4711** [comment]
사용자 가이드가 작성한지 좀 되어 조금 차이가 있습니다.
현재는 다운로드가 기본적으로 활성화되어있으며 상단에 다운로드 아이콘 버튼이 보이실거에요.
최근 발생한 문제인 크롬 버전 이슈로 인해 다운로드가 안되실 수도 있는데
현재 스토어 검수중인 1.9버전에서는 해결되었으며
자세한 내용 및 임시 해결 방안에 대해서는 인 앱 안내사항을 확인 부탁드리겠습니다.

**Comment by GregHKim** [comment]
저는 아직 다운로드 버튼이 안보이네요 ㅠㅠ 인 앱 내 안내사항도 확인이 힘들구요 ㅠ  스토어에 업데이트 되는 1.9버젼 기다려보겠습니다!

**Comment by GregHKim** [comment]
![스크린샷 2024-09-08 201425](https://github.com/user-attachments/assets/8a2dc9b8-f44d-4f4d-b0a3-8dc8952315e9)

아이콘 우클릭으로 어떻게든 옵션에 들어가보았는데 어떤 폴더를 선택하는 권한 X라고 나오더라구요 혹시 이슈가 이부분에서 오는걸까요? 크롬 extension 말고 gui 버전은 없으신지 궁금하네요 ^^... 유저들을 위해 해주시는 노력 감사합니다!
