### ISSUE TITLE
캐시를 삭제했더니 작동하지 않습니다

### ISSUE THREAD

**Issue by garubanana2** [lsh4711/rabbit-downloader#61]
캐시와 쿠키를 한번 지웠더니 다운로드 버튼이 아예 뜨질않습니다. 재설치해도 해결되지 않습니다.

**Comment by lsh4711** [comment]
해당 이슈는 이슈 #59 에서 확인 후 1.11 버전에서 해결했지만
운영 중단 일정과 겹쳐서 토끼 다운로더를 더이상 이용하실 수 없습니다.
