### ISSUE TITLE
구글 계정 로그인이 실패합니다

### ISSUE THREAD

**Issue by TK-DANGUL** [lsh4711/rabbit-downloader#62]
사용중인 운영체제
예시) 윈도우10
사용중인 브라우저와 버전
예시) 크롬 130.0.6723.91
문제 상황
로그인 계정 실패 문제 및 다운로더 가 사라졌어요

**Comment by lsh4711** [comment]
해당 이슈는 이슈 #59 에서 확인 후 1.11 버전에서 해결했지만
운영 중단 일정과 겹쳐서 토끼 다운로더를 더이상 이용하실 수 없습니다.
